import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

function readRepoFile(path: string): string {
  return readFileSync(fileURLToPath(new URL(`../${path}`, import.meta.url)), "utf8");
}

describe("playtest rollup template", () => {
  it("keeps a five-session rollup tied to the protocol thresholds", () => {
    const rollup = readRepoFile("docs/playtest_rollup_template.md");

    expect(rollup).toContain("Use this after five completed tester sessions");
    expect(rollup).toContain("at least 4 of 5");
    expect(rollup).toContain("at least 3 of 5");
    expect(rollup).toContain("Engagement and degraded visual intent observed");
    expect(rollup).toContain("Strongest evidence that play stayed engaging and the visual style landed");
    expect(rollup).toContain("5 of 5, no systematic complaint");
    expect(rollup).toContain("all mobile sessions");
    expect(rollup).toContain("Run ID");
    expect(rollup).toContain("Start Source");
    expect(rollup).toContain("Input");
    expect(rollup).toContain("npm run playtest:evaluate");
    expect(rollup).toContain("npm run playtest:rollup");
    expect(rollup).toContain("npm run playtest:evaluate-rollup");
    expect(rollup).toContain("docs/playtest_rollup_completed.md");
    expect(rollup).toContain("placeholder metadata values");
    expect(rollup).toContain("debrief answers");
    expect(rollup).toContain("real phone/tablet touch coverage");
    expect(rollup).toContain("concrete visual evidence");
    expect(rollup).toContain("screen recording, or observer-note evidence");
    expect(rollup).toContain("per-criterion evidence text");
    expect(rollup).toContain("criterion-specific pass evidence");
    expect(rollup).toContain("aggregate signals without numeric counts or concrete observed");
    expect(rollup).toContain("The first three fields require");
    expect(rollup).toContain("area-specific behavior");
    expect(rollup).toContain("Desktop touchscreens, trackpads, and");
    expect(rollup).toContain("browser emulation do not count");
    expect(rollup).toContain("## Principle Embodiment Audit");
    expect(rollup).toContain("docs/game_design_principles.md");
    expect(rollup).toContain("Top game design");
    expect(rollup).toContain("Critical/conceptual play");
    expect(rollup).toContain("Emotional design");
    expect(rollup).toContain("Game feel");
    expect(rollup).toContain("Optimal visual display");
    expect(rollup).toContain("Major principles embodied");
  });

  it("keeps the protocol and README linked to the rollup artifact", () => {
    const protocol = readRepoFile("docs/user_playtest_protocol.md");
    const readme = readRepoFile("README.md");
    const matrix = readRepoFile("docs/design_verification_matrix.md");
    const sessionTemplate = readRepoFile("docs/playtest_session_notes_template.md");
    const facilitatorCard = readRepoFile("docs/playtest_facilitator_card.md");

    expect(protocol).toContain("docs/playtest_rollup_template.md");
    expect(protocol).toContain("docs/playtest_facilitator_card.md");
    expect(protocol).toContain("docs/playtests/session-1.md");
    expect(protocol).toContain("npm run playtest:notes");
    expect(protocol).toContain("table-side no-coaching script");
    expect(protocol).toContain("npm run playtest:evaluate");
    expect(protocol).toContain("npm run playtest:rollup");
    expect(protocol).toContain("npm run playtest:evaluate-rollup");
    expect(protocol).toContain("npm run playtest:audit");
    expect(protocol).toContain("rollup/session consistency");
    expect(protocol).toContain("run IDs, input, copied-summary start source");
    expect(protocol).toContain("Recommended tester launch URL");
    expect(protocol).toContain("Network` and `Launch URL` lines");
    expect(protocol).toContain("non-localhost `Launch URL`");
    expect(protocol).toContain("template-placeholder metadata values");
    expect(protocol).toContain("blank or bare debrief answers");
    expect(protocol).toContain("blank or bare observation-note rows");
    expect(protocol).toContain("contradictions between matching observation rows and");
    expect(protocol).toContain("debrief answers that do not address their specific question");
    expect(protocol).toContain("missing, ambiguous, or contradictory evidence");
    expect(protocol).toContain("verdicts without evidence text");
    expect(protocol).toContain("generic pass evidence");
    expect(protocol).toContain("generic principle");
    expect(protocol).toContain("game-generated `mtt-...` run ID shape");
    expect(protocol).toContain("criterion-specific");
    expect(protocol).toContain("observed behavior");
    expect(protocol).toContain("One-word evidence cells");
    expect(protocol).toContain("post-tutorial Endless run must report");
    expect(protocol).toContain("`Start: handoff screen`");
    expect(protocol).toContain("Round trace");
    expect(protocol).toContain("fixture round trace");
    expect(protocol).toContain("Save Summary");
    expect(protocol).toContain("download the same full text summary");
    expect(protocol).toContain("`Looked fine` is not enough evidence");
    expect(protocol).toContain("desktop touchscreens");
    expect(protocol).toContain("principle-embodiment audit");
    expect(protocol).toContain("docs/game_design_principles.md");
    expect(protocol).toContain("mistakes feel earned and recoverable");
    expect(protocol).toContain("degraded visual style reads as intentional");
    expect(protocol).toContain("What made you want to keep playing or stop?");
    expect(protocol).toContain("prompt, action, review evidence, economy consequence");
    expect(readme).toContain("npm run playtest:evaluate");
    expect(readme).toContain("npm run playtest:rollup");
    expect(readme).toContain("npm run playtest:evaluate-rollup");
    expect(readme).toContain("rollup evaluator exits non-zero");
    expect(readme).toContain("session metadata is");
    expect(readme).toContain("debrief answers are blank or bare");
    expect(readme).toContain("debrief answers do not address their specific question");
    expect(readme).toContain("observation-note rows are blank or bare");
    expect(readme).toContain("session evaluator rejects conflicts between matching rows");
    expect(readme).toContain("principle evidence notes are blank or");
    expect(readme).toContain("verdict lacks evidence text");
    expect(readme).toContain("criterion-specific observed behavior");
    expect(readme).toContain("continued play interest and intentional degraded visual style");
    expect(readme).toContain("game-generated `mtt-...`");
    expect(readme).toContain("mobile gate has no real");
    expect(readme).toContain("phone/tablet session with touch, pen, or mixed input");
    expect(readme).toContain("docs/playtest_facilitator_card.md");
    expect(readme).toContain("Recommended tester launch URL");
    expect(readme).toContain("Network` and");
    expect(readme).toContain("Launch URL` lines");
    expect(readme).toContain("non-localhost `Launch URL`");
    expect(readme).toContain("npm run playtest:notes");
    expect(readme).toContain("docs/playtest_rollup_template.md");
    expect(readme).toContain("principle-embodiment evidence");
    expect(readme).toContain("run/start/input/round-trace/cut-count");
    expect(readme).toContain("docs/playtests/README.md");
    expect(readme).toContain("rollup/session consistency");
    expect(readme).toContain("completed rollup's session index");
    expect(readme).toContain("blank field-note templates");
    expect(matrix).toContain("npm run playtest:audit");
    expect(matrix).toContain("consistency between rollup run IDs");
    expect(sessionTemplate).toContain("docs/playtest_facilitator_card.md");
    expect(sessionTemplate).toContain("table-side no-coaching script");
    expect(sessionTemplate).toContain("The evaluator rejects blank fields and template-placeholder");
    expect(sessionTemplate).toContain("game-generated `mtt-...` format");
    expect(sessionTemplate).toContain("The evaluator rejects blank answers and bare");
    expect(sessionTemplate).toContain("The evaluator rejects blank pass cells, blank evidence cells");
    expect(sessionTemplate).toContain("mobile readability notes that");
    expect(sessionTemplate).toContain("do not name mobile or non-mobile context");
    expect(sessionTemplate).toContain("Observation rows and pass-criteria rows must not contradict each other");
    expect(sessionTemplate).toContain("These rows are cross-checked against the Observation Notes rows");
    expect(sessionTemplate).toContain("answers that do not address the specific question");
    expect(sessionTemplate).toContain("token-boundary answer must describe");
    expect(sessionTemplate).toContain("| Criterion | Result | Evidence / contradiction |");
    expect(sessionTemplate).toContain("bare verdicts are rejected");
    expect(sessionTemplate).toContain("Evidence cells like `pass`, `yes`, `ok`, `fail`, or `ambiguous`");
    expect(sessionTemplate).toContain("Pass rows must name the observed behavior or concept");
    expect(sessionTemplate).toContain("round trace");
    expect(sessionTemplate).toContain("Save Summary");
    expect(sessionTemplate).toContain("downloaded text file");
    expect(sessionTemplate).toContain("post-tutorial Endless run should include `Start: handoff screen`");
    expect(sessionTemplate).toContain("Input evidence:");
    expect(sessionTemplate).toContain("browser pointer type");
    expect(sessionTemplate).toContain("does not replace `Device/browser`, `Network:");
    expect(sessionTemplate).toContain("real phone/tablet/mobile browser");
    expect(sessionTemplate).toContain("Vite's Network host rather than `localhost` or `127.0.0.1`");
    expect(sessionTemplate).toContain("- Visual evidence: screenshot / photo / screen recording / observer notes / none");
    expect(sessionTemplate).toContain("must record screenshot, photo");
    expect(sessionTemplate).toContain("Errors felt earned and recoverable");
    expect(sessionTemplate).toContain("Prompt, action, evidence, consequence, and next step");
    expect(sessionTemplate).toContain("Degraded visual style felt intentional and play invited another round");
    expect(sessionTemplate).toContain("What made you want to keep playing or stop?");
    expect(sessionTemplate).toContain("Engagement and degraded visual intent observed");
    expect(sessionTemplate).toContain("## Principle Evidence Notes");
    expect(sessionTemplate).toContain("Top game design loop evidence");
    expect(sessionTemplate).toContain("generic principle notes");
    expect(sessionTemplate).toContain("concrete playtest behavior for that");
    expect(facilitatorCard).toContain("Do not pre-explain tokenization");
    expect(facilitatorCard).toContain("Recommended tester launch URL");
    expect(facilitatorCard).toContain("Network and Launch URL lines");
    expect(facilitatorCard).toContain("blocked for more than 30 seconds");
    expect(facilitatorCard).toContain("What do you think this screen is asking you to do?");
    expect(facilitatorCard).toContain("Evidence is not `pass`/`yes`");
    expect(facilitatorCard).toContain("Observation rows and pass-criteria rows must agree");
    expect(facilitatorCard).toContain("Engagement/aesthetic evidence must name both");
    expect(facilitatorCard).toContain("real phone/tablet/mobile browser plus touch, pen");
    expect(facilitatorCard).toContain("non-localhost Launch URL");
    expect(facilitatorCard).toContain("A mobile readability pass must name a concrete artifact");
    expect(facilitatorCard).toContain("emulation, trackpads, and desktop touchscreens do not");
    expect(facilitatorCard).toContain("`Start: handoff screen`");
    expect(facilitatorCard).toContain("errors feel earned and recoverable");
    expect(facilitatorCard).toContain("five principle areas");
    expect(facilitatorCard).toContain("Copy Summary");
    expect(facilitatorCard).toContain("Save Summary");
    expect(facilitatorCard).toContain("fixture");
    expect(facilitatorCard).toContain("round trace");
    expect(matrix).toContain("docs/playtest_rollup_template.md");
    expect(matrix).toContain("docs/playtests/README.md");
    expect(matrix).toContain("prepared templates rather than completed evidence");
    expect(matrix).toContain("return-to-space cleanup of accidental ordinary-word duplicates");
    expect(matrix).toContain("docs/playtest_facilitator_card.md");
    expect(matrix).toContain("npm run playtest:notes");
    expect(matrix).toContain("npm run playtest:status");
    expect(matrix).toContain("non-overwriting session note files");
    expect(matrix).toContain("30-second neutral intervention rule");
    expect(matrix).toContain("npm run playtest:evaluate");
    expect(matrix).toContain("npm run playtest:rollup");
    expect(matrix).toContain("npm run playtest:evaluate-rollup");
    expect(matrix).toContain("placeholder session metadata");
    expect(matrix).toContain("engagement and degraded-visual-intent evidence");
    expect(matrix).toContain("blank or bare observation-note rows");
    expect(matrix).toContain("contradictions between matching observation rows and pass-criteria rows");
    expect(matrix).toContain("blank or bare debrief answers");
    expect(matrix).toContain("debrief answers that do not address their specific question");
    expect(matrix).toContain("verdicts without evidence text");
    expect(matrix).toContain("criterion-specific observed behavior");
    expect(matrix).toContain("generic principle evidence notes");
    expect(matrix).toContain("aggregate signals without numeric counts or concrete observed patterns");
    expect(matrix).toContain("area-specific playtest behavior");
    expect(matrix).toContain("missing fixture round traces");
    expect(matrix).toContain("text-file download fallback");
    expect(matrix).toContain("first-user phone/tablet viewport sweep");
    expect(matrix).toContain("principle-embodiment audit");
    expect(matrix).toContain("top game design, critical/conceptual play, emotional design, game feel, and optimal visual display");
    expect(matrix).toContain("run-ID mismatches");
    expect(matrix).toContain("non-game-shaped run IDs");
    expect(matrix).toContain("desktop/emulated touch evidence");
    expect(matrix).toContain("same-machine or localhost mobile metadata");
    expect(matrix).toContain("metadata scaffold that removes desktop, same-machine, and no-evidence options");
    expect(matrix).toContain("launch metadata labelled as planned setup rather than copy-ready session metadata");
    expect(matrix).toContain("thin mobile readability passes");
    expect(matrix).toContain("continued play interest and intentional degraded visual style");
  });
});
