import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

function readRepoFile(path: string): string {
  return readFileSync(fileURLToPath(new URL(`../${path}`, import.meta.url)), "utf8");
}

describe("playtest access", () => {
  it("keeps a LAN dev-server script for real touch-device sessions", () => {
    const packageJson = JSON.parse(readRepoFile("package.json")) as {
      scripts?: Record<string, string>;
    };

    expect(packageJson.scripts?.["dev:lan"]).toBe("vite --host 0.0.0.0");
    expect(packageJson.scripts?.["playtest:serve"]).toBe("vite --host 127.0.0.1 --port 5173 --strictPort");
    expect(packageJson.scripts?.["playtest:serve:lan"]).toBe("vite --host 0.0.0.0 --port 5173 --strictPort");
    expect(packageJson.scripts?.["playtest:links"]).toBe("tsx scripts/print-playtest-links.ts");
    expect(packageJson.scripts?.["playtest:qa-links"]).toBe("tsx scripts/print-playtest-qa-links.ts");
    expect(packageJson.scripts?.["playtest:brief"]).toBe("tsx scripts/report-playtest-brief.ts");
    expect(packageJson.scripts?.["playtest:doctor"]).toBe("tsx scripts/check-playtest-server.ts");
    expect(packageJson.scripts?.["playtest:launch-check"]).toBe("tsx scripts/check-playtest-launch.ts");
    expect(packageJson.scripts?.["playtest:notes"]).toBe("tsx scripts/prepare-playtest-notes.ts");
    expect(packageJson.scripts?.["playtest:status"]).toBe("tsx scripts/report-playtest-status.ts");
    expect(packageJson.scripts?.["playtest:preflight"]).toBe(
      "npm run generate:fixtures && npm run test && npm run build && npm run playtest:audit:local"
    );
    expect(packageJson.scripts?.["playtest:audit:local"]).toBe("tsx scripts/audit-playtest-readiness.ts --local");
    expect(packageJson.scripts?.["playtest:audit"]).toBe("tsx scripts/audit-playtest-readiness.ts");
    expect(packageJson.scripts?.["playtest:evaluate"]).toBe("tsx scripts/evaluate-playtest-notes.ts");
  });

  it("documents the trusted-network touch-device launch path", () => {
    const protocol = readRepoFile("docs/user_playtest_protocol.md");
    const readme = readRepoFile("README.md");
    const facilitatorCard = readRepoFile("docs/playtest_facilitator_card.md");
    const checklist = readRepoFile("docs/playtest_day_checklist.md");
    const audit = readRepoFile("docs/phase2_design_audit.md");

    expect(protocol).toContain("npm run playtest:serve");
    expect(protocol).toContain("npm run playtest:serve:lan");
    expect(protocol).toContain("docs/playtest_day_checklist.md");
    expect(protocol).toContain("npm run playtest:preflight");
    expect(protocol).toContain("npm run playtest:links");
    expect(protocol).toContain("npm run playtest:qa-links");
    expect(protocol).toContain("npm run playtest:brief");
    expect(protocol).toContain("npm run playtest:doctor");
    expect(protocol).toContain("Port hygiene");
    expect(protocol).toContain("lsof -nP -iTCP:<chosen-port> -sTCP:LISTEN");
    expect(protocol).toContain("confirmed stale Vite process");
    expect(protocol).toContain("npm run playtest:launch-check");
    expect(protocol).toContain("suggested free port");
    expect(protocol).toContain("same-machine-only");
    expect(protocol).toContain("Network-host launch checks failed");
    expect(protocol).toContain("copy-ready `Network` and `Launch URL` session-metadata lines");
    expect(protocol).toContain("Do not copy");
    expect(protocol).toContain("same-machine metadata into the required mobile note");
    expect(protocol).toContain("npm run playtest:notes");
    expect(protocol).toContain("npm run playtest:status");
    expect(protocol).toContain("npm run playtest:evaluate");
    expect(protocol).toContain("npm run playtest:audit");
    expect(protocol).toContain("regenerates tokenizer fixtures, runs tests, builds");
    expect(protocol).toContain("runs the local evidence audit");
    expect(protocol).toContain("npm run playtest:audit:local");
    expect(protocol).toContain("without overwriting completed notes");
    expect(protocol).toContain("blank session metadata");
    expect(protocol).toContain("?mode=protocol-results");
    expect(protocol).toContain("--port <chosen-port>");
    expect(protocol).toContain("strict playtest server");
    expect(protocol).toContain("strictPort");
    expect(protocol).toContain("current note status");
    expect(protocol).toContain("next session note target");
    expect(protocol).toContain("mobile-session requirement");
    expect(protocol).toContain("Ready for rollup");
    expect(protocol).toContain("observation/pass-criteria contradictions");
    expect(protocol).toContain("pass-criteria evidence");
    expect(protocol).toContain("full reset-safe deep-link");
    expect(protocol).toContain("Treat its launch metadata as planned setup only");
    expect(protocol).toContain("copy-ready for the exact running host");
    expect(protocol).toContain("not tester");
    expect(protocol).toContain("do not count as real mobile evidence");
    expect(protocol).toContain("same trusted network");
    expect(protocol).toContain("Network URL");
    expect(protocol).toContain("binds");
    expect(protocol).toContain("beyond localhost");
    expect(protocol).toContain("Recommended tester launch URL");
    expect(protocol).toContain("open the Recommended tester launch URL on");
    expect(protocol).toContain("exact host from Vite's Network URL");
    expect(protocol).toContain("same-machine same-port");
    expect(protocol).toContain("macOS firewall or VPN");
    expect(protocol).toContain("--host <network-host>");
    expect(protocol).toContain("Copy the");
    expect(protocol).toContain("Network` and `Launch URL` lines");
    expect(protocol).toContain("`Network` must be");
    expect(protocol).toContain("`127.0.0.1`");
    expect(protocol).toContain("browser emulation do not prove real phone/tablet readability");
    expect(protocol).toContain("For a mobile readability pass");
    expect(protocol).toContain("`Looked fine` is not enough evidence");
    expect(protocol).toContain("Input evidence:");
    expect(protocol).toContain("browser reported");
    expect(protocol).toContain("not enough for the mobile gate");
    expect(protocol).toContain("Save Summary");
    expect(readme).toContain("npm run playtest:preflight");
    expect(readme).toContain("npm run playtest:audit:local");
    expect(readme).toContain("npm run playtest:serve");
    expect(readme).toContain("npm run playtest:serve:lan");
    expect(readme).toContain("npm run playtest:links");
    expect(readme).toContain("planned localhost/LAN launch targets");
    expect(readme).toContain("Treat its launch metadata as planned setup only");
    expect(readme).toContain("npm run playtest:qa-links");
    expect(readme).toContain("npm run playtest:brief");
    expect(readme).toContain("npm run playtest:doctor");
    expect(readme).toContain("npm run playtest:launch-check");
    expect(readme).toContain("suggested free port");
    expect(readme).toContain("same-machine-only");
    expect(readme).toContain("copy-ready");
    expect(readme).toContain("Do not copy same-machine metadata into the required");
    expect(readme).toContain("npm run playtest:notes");
    expect(readme).toContain("npm run playtest:status");
    expect(readme).toContain("npm run playtest:evaluate");
    expect(readme).toContain("npm run playtest:audit");
    expect(readme).toContain("docs/playtest_day_checklist.md");
    expect(readme).toContain("qaFreezeElapsedMs");
    expect(readme).toContain("regenerates tokenizer fixtures, runs the test suite, builds");
    expect(readme).toContain("runs the local evidence audit");
    expect(readme).toContain("pin port `5173`");
    expect(readme).toContain("unnoticed fallback port");
    expect(readme).toContain("first five non-overwriting note files");
    expect(readme).toContain("template placeholders");
    expect(readme).toContain("?mode=protocol-results");
    expect(readme).toContain("Recommended tester launch URL");
    expect(readme).toContain("open that Recommended tester launch URL on the actual");
    expect(readme).toContain("Vite's Network URL");
    expect(readme).toContain("same-machine same-port");
    expect(readme).toContain("macOS");
    expect(readme).toContain("VPN isolation");
    expect(readme).toContain("current note status");
    expect(readme).toContain("next session note target");
    expect(readme).toContain("mobile-session");
    expect(readme).toContain("rollup-ready line");
    expect(readme).toContain("Observation/pass-criteria contradictions");
    expect(readme).toContain("pass-criteria evidence");
    expect(readme).toContain("Network` and");
    expect(readme).toContain("Launch URL` lines");
    expect(readme).toContain("`Network` must be `LAN`");
    expect(readme).toContain("not `localhost` or `127.0.0.1`");
    expect(readme).toContain("mobile gate has no real");
    expect(readme).toContain("phone/tablet session with touch, pen, or mixed input");
    expect(readme).toContain("non-localhost `Launch URL`");
    expect(readme).toContain("concrete screenshot, photo");
    expect(readme).toContain("Input evidence:");
    expect(readme).toContain("browser-reported pointer type");
    expect(facilitatorCard).toContain("npm run playtest:preflight");
    expect(facilitatorCard).toContain("npm run playtest:notes");
    expect(facilitatorCard).toContain("npm run playtest:doctor");
    expect(facilitatorCard).toContain("Port hygiene");
    expect(facilitatorCard).toContain("lsof -nP -iTCP:<chosen-port> -sTCP:LISTEN");
    expect(facilitatorCard).toContain("Do not kill a listener already");
    expect(facilitatorCard).toContain("npm run playtest:launch-check");
    expect(facilitatorCard).toContain("suggested free port");
    expect(facilitatorCard).toContain("same-machine-only");
    expect(facilitatorCard).toContain("copy-ready session-metadata lines");
    expect(facilitatorCard).toContain("Doctor or links output labelled `Planned Network`");
    expect(facilitatorCard).toContain("npm run playtest:serve:lan");
    expect(facilitatorCard).toContain("strict");
    expect(facilitatorCard).toContain("--port <chosen-port>");
    expect(facilitatorCard).toContain("npm run playtest:links");
    expect(facilitatorCard).toContain("npm run playtest:brief");
    expect(facilitatorCard).toContain("Recommended tester launch URL");
    expect(facilitatorCard).toContain("open the Recommended tester");
    expect(facilitatorCard).toContain("--host <network-host>");
    expect(facilitatorCard).toContain("same-machine same-port");
    expect(facilitatorCard).toContain("macOS firewall or VPN");
    expect(facilitatorCard).toContain("full QA deep-link list");
    expect(facilitatorCard).toContain("Network and Launch URL lines");
    expect(facilitatorCard).toContain("copy-ready");
    expect(facilitatorCard).toContain("Do not copy same-machine metadata into the required mobile note");
    expect(facilitatorCard).toContain("Mobile Note Validity Checklist");
    expect(facilitatorCard).toContain("desktop emulation, trackpads, and desktop touchscreens do not count");
    expect(facilitatorCard).toContain("leave the required mobile note blank");
    expect(facilitatorCard).toContain("Input");
    expect(facilitatorCard).toContain("evidence");
    expect(facilitatorCard).toContain("next session note is required");
    expect(facilitatorCard).toContain("Save Summary");
    expect(facilitatorCard).toContain("trusted");
    expect(facilitatorCard).toContain("network");
    expect(facilitatorCard).toContain("real phone/tablet/mobile browser");
    expect(facilitatorCard).toContain("`Network: LAN`");
    expect(facilitatorCard).toContain("non-localhost Launch URL");
    expect(facilitatorCard).toContain("A mobile readability pass must name a concrete artifact");
    expect(checklist).toContain("npm run playtest:preflight");
    expect(checklist).toContain("npm run playtest:doctor");
    expect(checklist).toContain("Port hygiene");
    expect(checklist).toContain("lsof -nP -iTCP:<chosen-port> -sTCP:LISTEN");
    expect(checklist).toContain("Do not kill a listener already");
    expect(checklist).toContain("npm run playtest:launch-check");
    expect(checklist).toContain("suggested free port");
    expect(checklist).toContain("same-machine-only");
    expect(checklist).toContain("copy-ready metadata lines");
    expect(checklist).toContain("Doctor or links output that says `Planned Network`");
    expect(checklist).toContain("npm run playtest:serve");
    expect(checklist).toContain("npm run playtest:serve:lan");
    expect(checklist).toContain("strict port `5173`");
    expect(checklist).toContain("npm run playtest:brief -- --port <chosen-port>");
    expect(checklist).toContain("npm run playtest:qa-links -- --port <chosen-port>");
    expect(checklist).toContain("Recommended tester launch URL");
    expect(checklist).toContain("actual device before the tester arrives");
    expect(checklist).toContain("exact host from Vite's Network URL");
    expect(checklist).toContain("same-machine same-port");
    expect(checklist).toContain("macOS firewall or VPN");
    expect(checklist).toContain("Launch URL using");
    expect(checklist).toContain("not `localhost` or `127.0.0.1`");
    expect(checklist).toContain("copy-ready");
    expect(checklist).toContain("Do not copy same-machine metadata into the required mobile note");
    expect(checklist).toContain("Mobile Note Validity Checklist");
    expect(checklist).toContain("explicit `--host <network-host>` launch-check");
    expect(checklist).toContain("mobile note blank and fix the LAN path");
    expect(checklist).toContain("not tester sessions or mobile evidence");
    expect(checklist).toContain("next session note is the required real phone/tablet");
    expect(checklist).toContain("Ready for rollup evaluator: no");
    expect(checklist).toContain("full deep-link list");
    expect(checklist).toContain("Do not pre-explain");
    expect(checklist).toContain("finger occlusion");
    expect(checklist).toContain("Start: handoff screen");
    expect(checklist).toContain("Input evidence");
    expect(checklist).toContain("does not satisfy the mobile gate");
    expect(checklist).toContain("npm run playtest:evaluate-rollup -- docs/playtest_rollup_completed.md");
    expect(checklist).toContain("npm run playtest:audit");
    expect(checklist).toContain("At least one real phone/tablet touch");
    expect(audit).toContain("npm run playtest:links");
    expect(audit).toContain("same-machine same-port");
    expect(audit).toContain("macOS firewall or VPN");
    expect(audit).toContain("launch metadata labelled as planned setup");
    expect(audit).toContain("rather than copy-ready session");
    expect(audit).toContain("metadata until brief or launch-check verifies the exact running host");
    expect(audit).toContain("observation/pass-criteria contradictions treated as incomplete pass-criteria");
  });
});
